print ("tasoo"[::-1])
print ("tasii"[-4])

print(ord('A'))
print(ord('B'))
print(ord('C'))
print(ord('E'))
print(ord('F'))
print(ord('G'))
print(ord('H'))
print(ord('I'))
print(ord('J'))
print(ord('K'))
print(ord('L'))
print(ord('M'))
print(ord('N'))
print(ord('O'))
print(ord('P'))
print(ord('Q'))
print(ord('R'))
print(ord('S'))
print(ord('T'))
print(ord('U'))
print(ord('V'))
print(ord('W'))
print(ord('X'))
print(ord('Y'))
print(ord('Z'))